/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuralisRatingRegistry {
  export type RatingStruct = {
    assetId: BytesLike;
    ratingHash: BytesLike;
    grade: BigNumberish;
    riskScore: BigNumberish;
    methodologyVersion: BigNumberish;
    metadataURI: string;
    submitter: AddressLike;
    official: boolean;
    timestamp: BigNumberish;
  };

  export type RatingStructOutput = [
    assetId: string,
    ratingHash: string,
    grade: bigint,
    riskScore: bigint,
    methodologyVersion: bigint,
    metadataURI: string,
    submitter: string,
    official: boolean,
    timestamp: bigint
  ] & {
    assetId: string;
    ratingHash: string;
    grade: bigint;
    riskScore: bigint;
    methodologyVersion: bigint;
    metadataURI: string;
    submitter: string;
    official: boolean;
    timestamp: bigint;
  };
}

export interface AuralisRatingRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorRating"
      | "approvedPublishers"
      | "decisionHashUsed"
      | "decisions"
      | "latestRating"
      | "logDecision"
      | "nextDecisionId"
      | "owner"
      | "pause"
      | "paused"
      | "ratingAt"
      | "ratingHashUsed"
      | "ratingHistoryLength"
      | "renounceOwnership"
      | "setPublisher"
      | "transferOwnership"
      | "unpause"
      | "verifyRating"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecisionLogged"
      | "OwnershipTransferred"
      | "Paused"
      | "PublisherUpdated"
      | "RatingAnchored"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorRating",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedPublishers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decisionHashUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decisions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRating",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logDecision",
    values: [BytesLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextDecisionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ratingAt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ratingHashUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ratingHistoryLength",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPublisher",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyRating",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedPublishers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decisionHashUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decisions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextDecisionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ratingAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ratingHashUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratingHistoryLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyRating",
    data: BytesLike
  ): Result;
}

export namespace DecisionLoggedEvent {
  export type InputTuple = [
    decisionId: BigNumberish,
    decisionHash: BytesLike,
    agent: AddressLike,
    actionType: BytesLike,
    riskScore: BigNumberish
  ];
  export type OutputTuple = [
    decisionId: bigint,
    decisionHash: string,
    agent: string,
    actionType: string,
    riskScore: bigint
  ];
  export interface OutputObject {
    decisionId: bigint;
    decisionHash: string;
    agent: string;
    actionType: string;
    riskScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublisherUpdatedEvent {
  export type InputTuple = [publisher: AddressLike, approved: boolean];
  export type OutputTuple = [publisher: string, approved: boolean];
  export interface OutputObject {
    publisher: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingAnchoredEvent {
  export type InputTuple = [
    assetId: BytesLike,
    ratingHash: BytesLike,
    grade: BigNumberish,
    riskScore: BigNumberish,
    submitter: AddressLike,
    official: boolean,
    metadataURI: string
  ];
  export type OutputTuple = [
    assetId: string,
    ratingHash: string,
    grade: bigint,
    riskScore: bigint,
    submitter: string,
    official: boolean,
    metadataURI: string
  ];
  export interface OutputObject {
    assetId: string;
    ratingHash: string;
    grade: bigint;
    riskScore: bigint;
    submitter: string;
    official: boolean;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuralisRatingRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AuralisRatingRegistry;
  waitForDeployment(): Promise<this>;

  interface: AuralisRatingRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorRating: TypedContractMethod<
    [
      assetId: BytesLike,
      ratingHash: BytesLike,
      grade: BigNumberish,
      riskScore: BigNumberish,
      methodologyVersion: BigNumberish,
      metadataURI: string
    ],
    [boolean],
    "nonpayable"
  >;

  approvedPublishers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  decisionHashUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  decisions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        decisionHash: string;
        agent: string;
        actionType: string;
        riskScore: bigint;
        metadataURI: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  latestRating: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        bigint
      ] & {
        assetId: string;
        ratingHash: string;
        grade: bigint;
        riskScore: bigint;
        methodologyVersion: bigint;
        metadataURI: string;
        submitter: string;
        official: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  logDecision: TypedContractMethod<
    [
      decisionHash: BytesLike,
      actionType: BytesLike,
      riskScore: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  nextDecisionId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  ratingAt: TypedContractMethod<
    [assetId: BytesLike, index: BigNumberish],
    [AuralisRatingRegistry.RatingStructOutput],
    "view"
  >;

  ratingHashUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  ratingHistoryLength: TypedContractMethod<
    [assetId: BytesLike],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPublisher: TypedContractMethod<
    [publisher: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyRating: TypedContractMethod<
    [assetId: BytesLike, ratingHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorRating"
  ): TypedContractMethod<
    [
      assetId: BytesLike,
      ratingHash: BytesLike,
      grade: BigNumberish,
      riskScore: BigNumberish,
      methodologyVersion: BigNumberish,
      metadataURI: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvedPublishers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "decisionHashUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "decisions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        decisionHash: string;
        agent: string;
        actionType: string;
        riskScore: bigint;
        metadataURI: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestRating"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        bigint
      ] & {
        assetId: string;
        ratingHash: string;
        grade: bigint;
        riskScore: bigint;
        methodologyVersion: bigint;
        metadataURI: string;
        submitter: string;
        official: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "logDecision"
  ): TypedContractMethod<
    [
      decisionHash: BytesLike,
      actionType: BytesLike,
      riskScore: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextDecisionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "ratingAt"
  ): TypedContractMethod<
    [assetId: BytesLike, index: BigNumberish],
    [AuralisRatingRegistry.RatingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "ratingHashUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "ratingHistoryLength"
  ): TypedContractMethod<[assetId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPublisher"
  ): TypedContractMethod<
    [publisher: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyRating"
  ): TypedContractMethod<
    [assetId: BytesLike, ratingHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "DecisionLogged"
  ): TypedContractEvent<
    DecisionLoggedEvent.InputTuple,
    DecisionLoggedEvent.OutputTuple,
    DecisionLoggedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PublisherUpdated"
  ): TypedContractEvent<
    PublisherUpdatedEvent.InputTuple,
    PublisherUpdatedEvent.OutputTuple,
    PublisherUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RatingAnchored"
  ): TypedContractEvent<
    RatingAnchoredEvent.InputTuple,
    RatingAnchoredEvent.OutputTuple,
    RatingAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DecisionLogged(uint256,bytes32,address,bytes32,uint8)": TypedContractEvent<
      DecisionLoggedEvent.InputTuple,
      DecisionLoggedEvent.OutputTuple,
      DecisionLoggedEvent.OutputObject
    >;
    DecisionLogged: TypedContractEvent<
      DecisionLoggedEvent.InputTuple,
      DecisionLoggedEvent.OutputTuple,
      DecisionLoggedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PublisherUpdated(address,bool)": TypedContractEvent<
      PublisherUpdatedEvent.InputTuple,
      PublisherUpdatedEvent.OutputTuple,
      PublisherUpdatedEvent.OutputObject
    >;
    PublisherUpdated: TypedContractEvent<
      PublisherUpdatedEvent.InputTuple,
      PublisherUpdatedEvent.OutputTuple,
      PublisherUpdatedEvent.OutputObject
    >;

    "RatingAnchored(bytes32,bytes32,uint8,uint8,address,bool,string)": TypedContractEvent<
      RatingAnchoredEvent.InputTuple,
      RatingAnchoredEvent.OutputTuple,
      RatingAnchoredEvent.OutputObject
    >;
    RatingAnchored: TypedContractEvent<
      RatingAnchoredEvent.InputTuple,
      RatingAnchoredEvent.OutputTuple,
      RatingAnchoredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
