/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AuralisComplianceAttestorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvedAttesters"
      | "attestations"
      | "checkHashUsed"
      | "getVerdict"
      | "isEligible"
      | "latestAttestationOf"
      | "mintAttestation"
      | "mintFee"
      | "nextAttestationId"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "revoke"
      | "setAttester"
      | "setMintFee"
      | "transferOwnership"
      | "unpause"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationMinted"
      | "AttestationRevoked"
      | "AttesterUpdated"
      | "MintFeeUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvedAttesters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkHashUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerdict",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligible",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestAttestationOf",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAttestation",
    values: [
      AddressLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "mintFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextAttestationId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttester",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approvedAttesters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkHashUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVerdict", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isEligible", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestAttestationOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextAttestationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMintFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AttestationMintedEvent {
  export type InputTuple = [
    id: BigNumberish,
    subject: AddressLike,
    assetClassId: BytesLike,
    verdict: BigNumberish,
    attester: AddressLike,
    validUntil: BigNumberish,
    metadataURI: string
  ];
  export type OutputTuple = [
    id: bigint,
    subject: string,
    assetClassId: string,
    verdict: bigint,
    attester: string,
    validUntil: bigint,
    metadataURI: string
  ];
  export interface OutputObject {
    id: bigint;
    subject: string;
    assetClassId: string;
    verdict: bigint;
    attester: string;
    validUntil: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationRevokedEvent {
  export type InputTuple = [id: BigNumberish, by: AddressLike];
  export type OutputTuple = [id: bigint, by: string];
  export interface OutputObject {
    id: bigint;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttesterUpdatedEvent {
  export type InputTuple = [attester: AddressLike, approved: boolean];
  export type OutputTuple = [attester: string, approved: boolean];
  export interface OutputObject {
    attester: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintFeeUpdatedEvent {
  export type InputTuple = [fee: BigNumberish];
  export type OutputTuple = [fee: bigint];
  export interface OutputObject {
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuralisComplianceAttestor extends BaseContract {
  connect(runner?: ContractRunner | null): AuralisComplianceAttestor;
  waitForDeployment(): Promise<this>;

  interface: AuralisComplianceAttestorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvedAttesters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  attestations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        subject: string;
        attester: string;
        assetClassId: string;
        verdict: bigint;
        checkHash: string;
        jurisdictionTag: string;
        metadataURI: string;
        issuedAt: bigint;
        validUntil: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  checkHashUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getVerdict: TypedContractMethod<
    [wallet: AddressLike, assetClassId: BytesLike],
    [[bigint, boolean] & { verdict: bigint; active: boolean }],
    "view"
  >;

  isEligible: TypedContractMethod<
    [wallet: AddressLike, assetClassId: BytesLike],
    [boolean],
    "view"
  >;

  latestAttestationOf: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  mintAttestation: TypedContractMethod<
    [
      subject: AddressLike,
      assetClassId: BytesLike,
      verdict: BigNumberish,
      checkHash: BytesLike,
      jurisdictionTag: BytesLike,
      metadataURI: string,
      validitySeconds: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  mintFee: TypedContractMethod<[], [bigint], "view">;

  nextAttestationId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revoke: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  setAttester: TypedContractMethod<
    [attester: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setMintFee: TypedContractMethod<[fee: BigNumberish], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvedAttesters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        subject: string;
        attester: string;
        assetClassId: string;
        verdict: bigint;
        checkHash: string;
        jurisdictionTag: string;
        metadataURI: string;
        issuedAt: bigint;
        validUntil: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkHashUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getVerdict"
  ): TypedContractMethod<
    [wallet: AddressLike, assetClassId: BytesLike],
    [[bigint, boolean] & { verdict: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEligible"
  ): TypedContractMethod<
    [wallet: AddressLike, assetClassId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestAttestationOf"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintAttestation"
  ): TypedContractMethod<
    [
      subject: AddressLike,
      assetClassId: BytesLike,
      verdict: BigNumberish,
      checkHash: BytesLike,
      jurisdictionTag: BytesLike,
      metadataURI: string,
      validitySeconds: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextAttestationId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAttester"
  ): TypedContractMethod<
    [attester: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMintFee"
  ): TypedContractMethod<[fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AttestationMinted"
  ): TypedContractEvent<
    AttestationMintedEvent.InputTuple,
    AttestationMintedEvent.OutputTuple,
    AttestationMintedEvent.OutputObject
  >;
  getEvent(
    key: "AttestationRevoked"
  ): TypedContractEvent<
    AttestationRevokedEvent.InputTuple,
    AttestationRevokedEvent.OutputTuple,
    AttestationRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AttesterUpdated"
  ): TypedContractEvent<
    AttesterUpdatedEvent.InputTuple,
    AttesterUpdatedEvent.OutputTuple,
    AttesterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MintFeeUpdated"
  ): TypedContractEvent<
    MintFeeUpdatedEvent.InputTuple,
    MintFeeUpdatedEvent.OutputTuple,
    MintFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AttestationMinted(uint256,address,bytes32,uint8,address,uint64,string)": TypedContractEvent<
      AttestationMintedEvent.InputTuple,
      AttestationMintedEvent.OutputTuple,
      AttestationMintedEvent.OutputObject
    >;
    AttestationMinted: TypedContractEvent<
      AttestationMintedEvent.InputTuple,
      AttestationMintedEvent.OutputTuple,
      AttestationMintedEvent.OutputObject
    >;

    "AttestationRevoked(uint256,address)": TypedContractEvent<
      AttestationRevokedEvent.InputTuple,
      AttestationRevokedEvent.OutputTuple,
      AttestationRevokedEvent.OutputObject
    >;
    AttestationRevoked: TypedContractEvent<
      AttestationRevokedEvent.InputTuple,
      AttestationRevokedEvent.OutputTuple,
      AttestationRevokedEvent.OutputObject
    >;

    "AttesterUpdated(address,bool)": TypedContractEvent<
      AttesterUpdatedEvent.InputTuple,
      AttesterUpdatedEvent.OutputTuple,
      AttesterUpdatedEvent.OutputObject
    >;
    AttesterUpdated: TypedContractEvent<
      AttesterUpdatedEvent.InputTuple,
      AttesterUpdatedEvent.OutputTuple,
      AttesterUpdatedEvent.OutputObject
    >;

    "MintFeeUpdated(uint256)": TypedContractEvent<
      MintFeeUpdatedEvent.InputTuple,
      MintFeeUpdatedEvent.OutputTuple,
      MintFeeUpdatedEvent.OutputObject
    >;
    MintFeeUpdated: TypedContractEvent<
      MintFeeUpdatedEvent.InputTuple,
      MintFeeUpdatedEvent.OutputTuple,
      MintFeeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
