/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuralisPolicyGuard {
  export type RebalanceParamsStruct = {
    portfolioHash: BytesLike;
    topAssetBps: BigNumberish;
    topProtocolBps: BigNumberish;
    slippageBps: BigNumberish;
    aiConfidence: BigNumberish;
    liquidityScore: BigNumberish;
    notionalValue: BigNumberish;
    metadataURI: string;
  };

  export type RebalanceParamsStructOutput = [
    portfolioHash: string,
    topAssetBps: bigint,
    topProtocolBps: bigint,
    slippageBps: bigint,
    aiConfidence: bigint,
    liquidityScore: bigint,
    notionalValue: bigint,
    metadataURI: string
  ] & {
    portfolioHash: string;
    topAssetBps: bigint;
    topProtocolBps: bigint;
    slippageBps: bigint;
    aiConfidence: bigint;
    liquidityScore: bigint;
    notionalValue: bigint;
    metadataURI: string;
  };
}

export interface AuralisPolicyGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkRebalance"
      | "executeRebalance"
      | "lastRebalanceAt"
      | "nextRebalanceId"
      | "owner"
      | "policyOf"
      | "renounceOwnership"
      | "setPaused"
      | "setPolicy"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PolicyPausedSet"
      | "PolicyUpdated"
      | "RebalanceBlocked"
      | "RebalanceExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkRebalance",
    values: [AddressLike, AuralisPolicyGuard.RebalanceParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRebalance",
    values: [AuralisPolicyGuard.RebalanceParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRebalanceAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRebalanceId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policyOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setPolicy",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRebalanceAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRebalanceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policyOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyPausedSetEvent {
  export type InputTuple = [user: AddressLike, paused: boolean];
  export type OutputTuple = [user: string, paused: boolean];
  export interface OutputObject {
    user: string;
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyUpdatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceBlockedEvent {
  export type InputTuple = [user: AddressLike, reason: string];
  export type OutputTuple = [user: string, reason: string];
  export interface OutputObject {
    user: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceExecutedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    portfolioHash: BytesLike,
    notionalValue: BigNumberish,
    metadataURI: string
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    portfolioHash: string,
    notionalValue: bigint,
    metadataURI: string
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    portfolioHash: string;
    notionalValue: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuralisPolicyGuard extends BaseContract {
  connect(runner?: ContractRunner | null): AuralisPolicyGuard;
  waitForDeployment(): Promise<this>;

  interface: AuralisPolicyGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkRebalance: TypedContractMethod<
    [user: AddressLike, p: AuralisPolicyGuard.RebalanceParamsStruct],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;

  executeRebalance: TypedContractMethod<
    [p: AuralisPolicyGuard.RebalanceParamsStruct],
    [bigint],
    "nonpayable"
  >;

  lastRebalanceAt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  nextRebalanceId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policyOf: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        maxPerAssetBps: bigint;
        maxPerProtocolBps: bigint;
        maxSlippageBps: bigint;
        minConfidence: bigint;
        minLiquidityScore: bigint;
        cooldownSeconds: bigint;
        humanApprovalThreshold: bigint;
        exists: boolean;
        paused: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPaused: TypedContractMethod<[paused: boolean], [void], "nonpayable">;

  setPolicy: TypedContractMethod<
    [
      maxPerAssetBps: BigNumberish,
      maxPerProtocolBps: BigNumberish,
      maxSlippageBps: BigNumberish,
      minConfidence: BigNumberish,
      minLiquidityScore: BigNumberish,
      cooldownSeconds: BigNumberish,
      humanApprovalThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkRebalance"
  ): TypedContractMethod<
    [user: AddressLike, p: AuralisPolicyGuard.RebalanceParamsStruct],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeRebalance"
  ): TypedContractMethod<
    [p: AuralisPolicyGuard.RebalanceParamsStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastRebalanceAt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextRebalanceId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyOf"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        maxPerAssetBps: bigint;
        maxPerProtocolBps: bigint;
        maxSlippageBps: bigint;
        minConfidence: bigint;
        minLiquidityScore: bigint;
        cooldownSeconds: bigint;
        humanApprovalThreshold: bigint;
        exists: boolean;
        paused: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPolicy"
  ): TypedContractMethod<
    [
      maxPerAssetBps: BigNumberish,
      maxPerProtocolBps: BigNumberish,
      maxSlippageBps: BigNumberish,
      minConfidence: BigNumberish,
      minLiquidityScore: BigNumberish,
      cooldownSeconds: BigNumberish,
      humanApprovalThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyPausedSet"
  ): TypedContractEvent<
    PolicyPausedSetEvent.InputTuple,
    PolicyPausedSetEvent.OutputTuple,
    PolicyPausedSetEvent.OutputObject
  >;
  getEvent(
    key: "PolicyUpdated"
  ): TypedContractEvent<
    PolicyUpdatedEvent.InputTuple,
    PolicyUpdatedEvent.OutputTuple,
    PolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceBlocked"
  ): TypedContractEvent<
    RebalanceBlockedEvent.InputTuple,
    RebalanceBlockedEvent.OutputTuple,
    RebalanceBlockedEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceExecuted"
  ): TypedContractEvent<
    RebalanceExecutedEvent.InputTuple,
    RebalanceExecutedEvent.OutputTuple,
    RebalanceExecutedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicyPausedSet(address,bool)": TypedContractEvent<
      PolicyPausedSetEvent.InputTuple,
      PolicyPausedSetEvent.OutputTuple,
      PolicyPausedSetEvent.OutputObject
    >;
    PolicyPausedSet: TypedContractEvent<
      PolicyPausedSetEvent.InputTuple,
      PolicyPausedSetEvent.OutputTuple,
      PolicyPausedSetEvent.OutputObject
    >;

    "PolicyUpdated(address)": TypedContractEvent<
      PolicyUpdatedEvent.InputTuple,
      PolicyUpdatedEvent.OutputTuple,
      PolicyUpdatedEvent.OutputObject
    >;
    PolicyUpdated: TypedContractEvent<
      PolicyUpdatedEvent.InputTuple,
      PolicyUpdatedEvent.OutputTuple,
      PolicyUpdatedEvent.OutputObject
    >;

    "RebalanceBlocked(address,string)": TypedContractEvent<
      RebalanceBlockedEvent.InputTuple,
      RebalanceBlockedEvent.OutputTuple,
      RebalanceBlockedEvent.OutputObject
    >;
    RebalanceBlocked: TypedContractEvent<
      RebalanceBlockedEvent.InputTuple,
      RebalanceBlockedEvent.OutputTuple,
      RebalanceBlockedEvent.OutputObject
    >;

    "RebalanceExecuted(uint256,address,bytes32,uint256,string)": TypedContractEvent<
      RebalanceExecutedEvent.InputTuple,
      RebalanceExecutedEvent.OutputTuple,
      RebalanceExecutedEvent.OutputObject
    >;
    RebalanceExecuted: TypedContractEvent<
      RebalanceExecutedEvent.InputTuple,
      RebalanceExecutedEvent.OutputTuple,
      RebalanceExecutedEvent.OutputObject
    >;
  };
}
