import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Button, MktSection, PageHero, PillarGraphic } from "../../../components/marketing";

export default function Product(){
  const pillars = [
    { title:"Rate", subtitle:"Asset Intelligence", kind:"rating" as const, points:["Composite 0–100 risk score and AAA–C letter grade","Seven dimensions, each with a published rationale","Continuous monitoring with depeg and oracle watchers","Every rating versioned, hashed, and anchored on Mantle"]},
    { title:"Verify", subtitle:"Compliance & Eligibility", kind:"eligibility" as const, points:["Wallet screen with sanctions and counterparty heuristics","Eligibility verdicts per asset and per jurisdiction","Portable compliance reports and on-chain attestations","Quiet 'not legal advice' notice on every surface"]},
    { title:"Manage", subtitle:"Portfolio Agent", kind:"simulator" as const, points:["AI proposes; you approve. Always.","Seven hard guardrails enforced before any execution","Before/after simulation with allocation preview","Decisions and proofs in one auditable trail"]},
  ];
  return <main><PageHero eyebrow="Product" title="The three things Auralis does.">One closed loop — Rate, Verify, Manage. Each pillar is its own surface in the app. Together they make tokenized real-world yield safe to hold at size.</PageHero>{pillars.map((p,i)=><MktSection key={p.title} muted={i===1}><div className="grid items-center gap-12 lg:grid-cols-2"><div className={i===1?"lg:order-2":""}><div className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--teal)]">Pillar {String(i+1).padStart(2,"0")}</div><h2 className="mt-3 font-display text-5xl leading-tight tracking-[-0.03em]">{p.title}.<br/><span className="text-[var(--text-secondary)]">{p.subtitle}.</span></h2><ul className="mt-6 grid gap-3">{p.points.map(pt=><li key={pt} className="flex gap-3 text-[15px]"><Check size={17} className="mt-0.5 shrink-0 text-[var(--teal)]"/>{pt}</li>)}</ul></div><div className={i===1?"lg:order-1":""}><PillarGraphic kind={p.kind}/></div></div></MktSection>)}<MktSection><div className="text-center"><h2 className="font-display text-5xl tracking-[-0.03em]">One closed loop.</h2><p className="mt-4 text-lg text-[var(--text-secondary)]">Observe → Rate → Verify → Simulate → Approve → Execute → Prove.</p><Link href="/docs"><Button className="mt-8" variant="secondary">Read the docs <ArrowRight size={14}/></Button></Link></div></MktSection></main>;
}
