import Link from "next/link";
import { ArrowRight, Award, Check, ChevronDown, Database, FileText, Globe2, Layers, Lock, Network, Search, ShieldCheck, Sparkles, Star, Wallet } from "lucide-react";
import { Button, Card, RatingSeal, RiskRadar, StatusPill } from "@auralis/ui";

export const assets = [
  { id: "mantle:usdy", symbol: "USDY", name: "Ondo US Dollar Yield", klass: "US Treasury RWA", grade: "A", score: 28, apy: 4.85, tvl: "$42.8M", trend: "+0.42%", dims: [28, 34, 42, 18, 31, 26, 39], hash: "0x8f24a1c9…e7b3d2" },
  { id: "mantle:qcdt", symbol: "QCDT", name: "QCD Money Market", klass: "Private credit", grade: "BBB", score: 51, apy: 8.12, tvl: "$19.4M", trend: "+1.04%", dims: [44, 48, 54, 41, 37, 39, 62], hash: "0x72bc5d19…44f0aa" },
  { id: "mantle:meth", symbol: "mETH", name: "Mantle Staked Ether", klass: "Liquid staking", grade: "AA", score: 22, apy: 3.15, tvl: "$128.2M", trend: "+0.18%", dims: [18, 24, 26, 12, 21, 29, 33], hash: "0xa3e97c0b…19d84e" },
  { id: "mantle:cmeth", symbol: "cmETH", name: "Compounding mETH", klass: "Liquid staking", grade: "A", score: 31, apy: 3.74, tvl: "$76.1M", trend: "+0.25%", dims: [24, 30, 34, 20, 28, 31, 41], hash: "0x91be47a2…7f2a30" },
  { id: "mantle:usde", symbol: "USDe", name: "Ethena USDe", klass: "Synthetic dollar", grade: "BBB", score: 48, apy: 8.40, tvl: "$64.5M", trend: "+0.88%", dims: [38, 45, 49, 58, 36, 43, 67], hash: "0x4dc21f70…b6a8c1" },
  { id: "mantle:mi4", symbol: "MI4", name: "Mantle Index Four", klass: "RWA index", grade: "A", score: 36, apy: 6.35, tvl: "$22.9M", trend: "+0.61%", dims: [32, 38, 44, 30, 35, 28, 49], hash: "0xbd30a94f…c82e11" },
  { id: "mantle:aave", symbol: "AAVE", name: "Aave Mantle Market", klass: "Regulated yield", grade: "AA", score: 24, apy: 5.18, tvl: "$98.7M", trend: "+0.33%", dims: [20, 27, 23, 18, 19, 22, 34], hash: "0xc648ef12…50ad93" },
  { id: "mantle:moe", symbol: "MOE-LP", name: "Merchant Moe LP", klass: "DEX liquidity", grade: "BB", score: 63, apy: 11.92, tvl: "$12.6M", trend: "-0.27%", dims: [61, 52, 58, 66, 48, 54, 73], hash: "0xf1906b4c…2e9a75" },
];

export const footerColumns = [
  ["Product", [["Overview", "/product"], ["Ratings", "/ratings"], ["Methodology", "/methodology"], ["Open app", "/app"]]],
  ["Resources", [["Documentation", "/docs"], ["Security", "/security"], ["FAQ", "/faq"]]],
  ["Company", [["About", "/company"], ["Business model", "/business"], ["Press", "/company"]]],
  ["Legal", [["Terms", "/docs"], ["Privacy", "/docs"], ["Disclosures", "/security"]]],
] as const;

export function BrandMark({ light = false }: { light?: boolean }) {
  return <span className="relative inline-grid h-6 w-6 place-items-center rounded-full" aria-hidden="true"><span className={`absolute inset-0 rounded-full border-2 ${light ? "border-white/30" : "border-[var(--teal-wash)]"}`} /><span className={`absolute h-5 w-5 rounded-full border-2 border-r-transparent border-b-transparent ${light ? "border-white" : "border-[var(--teal)]"}`} /><span className={`h-2 w-2 rounded-full ${light ? "bg-white" : "bg-[var(--teal)]"}`} /></span>;
}

export function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="font-sans text-xs font-semibold uppercase tracking-[0.14em] text-[var(--teal)]">{children}</div>; }
export function PageHero({ eyebrow, title, children, narrow = false }: { eyebrow: string; title: string; children: React.ReactNode; narrow?: boolean }) { return <section className="mx-auto max-w-6xl px-4 pb-12 pt-16"><div className={narrow ? "max-w-3xl" : "max-w-4xl"}><Eyebrow>{eyebrow}</Eyebrow><h1 className="mt-3 font-display text-5xl font-normal leading-[0.96] tracking-[-0.03em] text-[var(--ink)] md:text-7xl">{title}</h1><p className="mt-5 text-lg leading-8 text-[var(--text-secondary)] md:text-xl">{children}</p></div></section>; }
export function SectionTitle({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-3 max-w-3xl font-display text-4xl font-normal leading-tight tracking-[-0.025em] md:text-5xl">{title}</h2>{children && <p className="mt-4 max-w-2xl text-lg leading-8 text-[var(--text-secondary)]">{children}</p>}</div>; }
export function MktSection({ children, muted = false, className = "" }: { children: React.ReactNode; muted?: boolean; className?: string }) { return <section className={`${muted ? "border-y border-[var(--border)] bg-[var(--surface)]" : ""} py-20 ${className}`}><div className="mx-auto max-w-6xl px-4">{children}</div></section>; }

export function ProductPreview() { return <div className="overflow-hidden rounded-[14px] border border-[var(--border)] bg-[var(--surface)] shadow-[0_24px_60px_rgba(11,18,32,0.12)]"><div className="flex items-center gap-2 border-b border-[var(--border)] bg-[var(--surface-muted)] px-4 py-2.5"><span className="h-2.5 w-2.5 rounded-full bg-[#E4836B]"/><span className="h-2.5 w-2.5 rounded-full bg-[#E2C166]"/><span className="h-2.5 w-2.5 rounded-full bg-[#7DBF8C]"/><span className="ml-3 flex-1 rounded-md bg-[var(--surface)] px-3 py-1 font-mono text-[11px] text-[var(--text-secondary)]">app.auralis.finance/dashboard</span></div><div className="p-4"><div className="mb-3 flex items-center justify-between"><div className="font-display text-lg">Portfolio Dashboard</div><StatusPill status="operational">Live</StatusPill></div><div className="grid gap-3 sm:grid-cols-4">{[["Value","$18.42M","+6.27%"],["APY","9.18%","+0.73%"],["Risk","42","Low"],["Liquidity","$1.78M",""]].map(([l,v,d])=><div key={l} className="rounded-[10px] bg-[var(--surface-muted)] p-3"><div className="text-xs text-[var(--text-secondary)]">{l}</div><div className="mt-1 font-display text-lg">{v}</div>{d && <div className="text-xs text-[var(--emerald)]">{d}</div>}</div>)}</div><div className="mt-3 grid gap-3 md:grid-cols-[200px_1fr]"><Donut /><div className="rounded-[10px] bg-[var(--surface-muted)] p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs uppercase tracking-wide text-[var(--text-secondary)]">Performance · 30D</span><StatusPill tone="emerald">+6.27%</StatusPill></div><LineChart /></div></div><div className="mt-3 overflow-hidden rounded-[var(--radius-card)] border border-[var(--border)]">{assets.slice(0,3).map((a)=><div key={a.symbol} className="flex items-center justify-between gap-3 border-t border-[var(--border)] px-3 py-2 first:border-t-0"><div className="flex items-center gap-3"><AssetIcon symbol={a.symbol}/><div><div className="text-sm font-medium">{a.name}</div><div className="text-xs text-[var(--text-secondary)]">{a.klass}</div></div></div><div className="flex items-center gap-4"><span className="font-mono text-xs">{a.tvl}</span><RatingSeal grade={a.grade} size="sm" /></div></div>)}</div></div></div>; }
export function Donut({ className = "" }: { className?: string }) { return <div className={`grid min-h-40 place-items-center rounded-[10px] bg-[var(--surface-muted)] p-4 ${className}`}><div className="grid h-36 w-36 place-items-center rounded-full" style={{background:"conic-gradient(var(--teal) 0 46%, #1F58A8 46% 78%, #8C97A8 78% 100%)"}}><div className="grid h-24 w-24 place-items-center rounded-full bg-[var(--surface)] text-center"><span className="font-display text-xl">$18.4M</span><span className="-mt-5 text-xs text-[var(--text-secondary)]">total</span></div></div></div>; }
export function LineChart() { const points="0,84 32,70 64,76 96,54 128,60 160,42 192,50 224,28 256,36 288,20 320,26"; return <svg viewBox="0 0 320 100" className="h-28 w-full"><defs><linearGradient id="lineFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--teal)" stopOpacity="0.22"/><stop offset="1" stopColor="var(--teal)" stopOpacity="0"/></linearGradient></defs><path d={`M ${points} L 320,100 L 0,100 Z`} fill="url(#lineFill)"/><polyline points={points} fill="none" stroke="var(--teal)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
export function AssetIcon({ symbol }: { symbol: string }) { return <span className="inline-grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[var(--teal-wash)] text-[11px] font-semibold text-[var(--teal)]">{symbol.slice(0,2)}</span>; }
export function Spark() { return <svg viewBox="0 0 64 20" className="h-5 w-16"><polyline points="0,14 8,11 16,13 24,8 32,10 40,5 48,7 56,3 64,6" fill="none" stroke="var(--teal)" strokeWidth="2" strokeLinecap="round"/></svg>; }

export function AssetGrid() { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{assets.map(a=><Link href={`/ratings/${a.id}`} key={a.id} className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-4 shadow-[var(--shadow-soft)] transition hover:-translate-y-0.5"><div className="flex items-center justify-between"><AssetIcon symbol={a.symbol}/><RatingSeal grade={a.grade} size="sm" /></div><div className="mt-3 font-medium">{a.name}</div><div className="text-xs text-[var(--text-secondary)]">{a.klass}</div><div className="mt-3 flex items-center justify-between text-sm"><span className="text-[var(--text-secondary)]">APY</span><span className="font-mono">{a.apy.toFixed(2)}%</span></div></Link>)}</div>; }
export function RatingTable() { return <div className="overflow-hidden rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-soft)]"><table className="w-full text-sm"><thead className="bg-[var(--surface-muted)] text-left text-xs uppercase tracking-wide text-[var(--text-secondary)]"><tr><th className="p-4">Asset</th><th className="p-4">Rating</th><th className="p-4">Risk score</th><th className="p-4">Risk-adj. APY</th><th className="p-4">TVL</th><th className="p-4">30D</th><th className="p-4"/></tr></thead><tbody>{assets.map(a=><tr key={a.id} className="border-t border-[var(--border)] hover:bg-[var(--teal-wash)]"><td className="p-4"><div className="flex items-center gap-3"><AssetIcon symbol={a.symbol}/><div><div className="font-medium">{a.name}</div><div className="text-xs text-[var(--text-secondary)]">{a.symbol} · {a.klass}</div></div></div></td><td className="p-4"><RatingSeal grade={a.grade} size="sm" /></td><td className="p-4"><div className="flex min-w-32 items-center gap-3"><span className="font-mono">{a.score}</span><span className="h-1.5 flex-1 overflow-hidden rounded-full bg-[var(--surface-muted)]"><span className="block h-full bg-[var(--teal)]" style={{width:`${a.score}%`}} /></span></div></td><td className="p-4 font-mono">{a.apy.toFixed(2)}%</td><td className="p-4 font-mono">{a.tvl}</td><td className="p-4"><Spark /></td><td className="p-4"><Link className="inline-flex items-center gap-1 text-sm font-medium text-[var(--teal)]" href={`/ratings/${a.id}`}>Details <ArrowRight size={13}/></Link></td></tr>)}</tbody></table></div>; }

export function PillarGraphic({ kind }: { kind: "rating" | "eligibility" | "simulator" }) { if (kind === "rating") { const a=assets[2]; return <Card className="p-7"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><AssetIcon symbol={a.symbol}/><div><div className="font-display text-2xl">{a.name}</div><div className="text-sm text-[var(--text-secondary)]">{a.klass}</div></div></div><RatingSeal grade={a.grade} size="lg"/></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><MiniStat label="Risk score" value={String(a.score)} pill="Low risk"/><MiniStat label="Risk-adj. APY" value={`${a.apy.toFixed(2)}%`}/></div></Card>; } if (kind === "eligibility") return <Card className="p-0"><div className="flex items-center justify-between border-b border-[var(--border)] p-5"><span className="text-xs font-semibold uppercase tracking-wide text-[var(--text-secondary)]">Eligibility · jurisdiction NG</span><StatusPill status="eligible">Wallet cleared</StatusPill></div>{assets.slice(0,5).map((a,i)=><div key={a.symbol} className="flex items-center justify-between border-t border-[var(--border)] px-5 py-3 first:border-t-0"><div className="flex items-center gap-3"><AssetIcon symbol={a.symbol}/><span className="text-sm">{a.name}</span></div><StatusPill status={i===1?"restricted":"eligible"}>{i===1?"Restricted":"Eligible"}</StatusPill></div>)}</Card>; return <Card className="p-7"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-wide text-[var(--text-secondary)]">Simulator · before → after</span><StatusPill tone="emerald">+0.24% APY</StatusPill></div><div className="flex items-center justify-center gap-6"><Donut className="min-h-0 bg-transparent p-0"/><ArrowRight className="text-[var(--text-secondary)]"/><Donut className="min-h-0 bg-transparent p-0"/></div></Card>; }
export function MiniStat({ label, value, pill }: { label: string; value: string; pill?: string }) { return <div className="rounded-[var(--radius-card)] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--shadow-soft)]"><div className="text-xs font-semibold uppercase tracking-wide text-[var(--text-secondary)]">{label}</div><div className="mt-2 font-display text-3xl">{value}</div>{pill && <div className="mt-3"><StatusPill status="eligible">{pill}</StatusPill></div>}</div>; }

export const icons = { Rate: Star, Verify: ShieldCheck, Manage: Sparkles, Network, Lock, ShieldCheck, Database, Award, FileText, Globe2, Layers, Wallet, Search, Check, ArrowRight, ChevronDown };
export { Link, Button, Card, RatingSeal, RiskRadar, StatusPill };
