import { ArrowRight, Check, Lock, Network, ShieldCheck, Sparkles, Star } from "lucide-react";
import { AssetGrid, Button, Card, Eyebrow, MktSection, ProductPreview, RiskRadar, SectionTitle, assets } from "../../components/marketing";
import Link from "next/link";

export default function Page() {
  const stats = [["34+", "Assets rated"], ["12,842", "Decisions logged"], ["1.28%", "Avg. yield uplift"], ["2,318", "Active users"]];
  const pillars = [
    [Star, "Asset Intelligence", "Rate", "Every tokenized real-world asset gets an Auralis Rating — a letter grade, a 0–100 risk score, and a seven-part risk breakdown."],
    [ShieldCheck, "Compliance & Eligibility", "Verify", "For your connected wallet, Auralis tells you whether you may hold each asset, and lets you mint an on-chain proof."],
    [Sparkles, "Portfolio Agent", "Manage", "An AI agent recommends and simulates rebalances under hard guardrails — you approve, it executes, every step proven on-chain."],
  ] as const;
  const loop = ["Observe", "Rate", "Verify", "Simulate", "Approve", "Execute", "Prove"];
  return <main>
    <section className="mx-auto grid max-w-6xl items-center gap-16 px-4 py-24 lg:grid-cols-[1.05fr_1fr]"><div><Eyebrow>Auralis · AI Risk & Compliance</Eyebrow><h1 className="mt-4 font-display text-6xl font-normal leading-[0.94] tracking-[-0.04em] text-[var(--ink)] md:text-7xl">Risk intelligence for real-world yield.</h1><p className="mt-6 max-w-2xl text-xl leading-8 text-[var(--text-secondary)]">Auralis is the AI agent that rates, compliance-checks, and rebalances tokenized real-world assets on Mantle — with every decision proven on-chain.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/app"><Button size="lg">Open App <ArrowRight size={15}/></Button></Link><Link href="/ratings"><Button size="lg" variant="secondary">View live ratings</Button></Link></div><div className="mt-6 flex flex-wrap gap-4 text-sm text-[var(--text-secondary)]">{["Non-custodial", "Every decision on-chain", "Built for transparency"].map(x=><span key={x} className="inline-flex items-center gap-2"><Check size={14} className="text-[var(--teal)]"/>{x}</span>)}</div></div><ProductPreview /></section>
    <section className="border-y border-[var(--border)] bg-[var(--surface-muted)] py-5"><div className="mx-auto flex max-w-6xl flex-wrap justify-between gap-5 px-4 text-sm font-medium text-[var(--text-secondary)]"><span className="inline-flex items-center gap-2"><Network size={14}/>Built on Mantle</span><span className="inline-flex items-center gap-2"><Lock size={14}/>Non-custodial by design</span><span className="inline-flex items-center gap-2"><ShieldCheck size={14}/>Every decision on-chain</span><span className="inline-flex items-center gap-2"><Sparkles size={14}/>Methodology v1.0 · published</span></div></section>
    <MktSection><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([v,l])=><div key={l}><div className="font-display text-5xl leading-none">{v}</div><div className="mt-2 text-xs font-semibold uppercase tracking-wide text-[var(--text-secondary)]">{l}</div></div>)}</div></MktSection>
    <MktSection muted><SectionTitle eyebrow="What Auralis does" title="Three things, in one closed loop." /><div className="mt-12 grid gap-6 md:grid-cols-3">{pillars.map(([Icon,label,title,copy])=><Card key={title} className="p-7"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[var(--teal-wash)] text-[var(--teal)]"><Icon size={20}/></div><div className="mt-5 text-xs font-semibold uppercase tracking-wide text-[var(--text-secondary)]">{label}</div><h3 className="mt-1 font-display text-3xl">{title}.</h3><p className="mt-3 text-[15px] leading-7 text-[var(--text-secondary)]">{copy}</p><Link href="/product" className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-[var(--teal)]">Learn more <ArrowRight size={14}/></Link></Card>)}</div></MktSection>
    <MktSection><SectionTitle eyebrow="The Auralis loop" title="Observe → Rate → Verify → Simulate → Approve → Execute → Prove.">Every action in Auralis follows the same seven-step path. Nothing is hidden. Every step is reproducible.</SectionTitle><div className="mt-12 flex flex-wrap justify-center gap-3">{loop.map((s,i)=><div key={s} className="flex items-center gap-3"><Card className="min-w-36 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-[var(--text-secondary)]">Step {String(i+1).padStart(2,"0")}</div><div className="mt-1 font-display text-xl">{s}</div></Card>{i<loop.length-1 && <ArrowRight size={14} className="hidden text-[var(--text-secondary)] sm:block"/>}</div>)}</div></MktSection>
    <MktSection muted><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><SectionTitle eyebrow="Supported assets" title="Rated and continuously monitored." /><Link href="/ratings"><Button variant="secondary">View all ratings <ArrowRight size={14}/></Button></Link></div><AssetGrid /></MktSection>
    <MktSection><div className="grid items-center gap-12 lg:grid-cols-[1.1fr_1fr]"><div><SectionTitle eyebrow="Methodology" title="Not a black box.">Every Auralis rating is built from seven dimensions: asset, issuer, liquidity, peg, oracle, smart-contract, and concentration. The composite score is published, versioned, and verifiable.</SectionTitle><Link href="/methodology"><Button className="mt-6" variant="secondary">Read the methodology <ArrowRight size={14}/></Button></Link></div><Card className="grid place-items-center p-8"><RiskRadar values={assets[0].dims} size={300}/></Card></div></MktSection>
    <section className="bg-[var(--ink)] py-28 text-center text-white"><div className="mx-auto max-w-3xl px-4"><h2 className="font-display text-5xl leading-tight tracking-[-0.03em]">The next trillion dollars won&apos;t be managed by banks.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-white/70">It will be managed by code, audited by AI, and proven on-chain. Auralis is the layer that makes that possible.</p><Link href="/app"><Button className="mt-8">Open App <ArrowRight size={14}/></Button></Link></div></section>
  </main>;
}
